stages:
  process_data:
    cmd: python src/processing.py
    deps:
    - src/processing.py
    outs:
    - data/intermediate
  train:
    cmd: python src/train.py
    deps:
    - data/intermediate
    - src/train.py
    outs:
    - model/decision_tree
    - model/decision_tree.mlem:
        cache: false
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - model/decision_tree
    - src/evaluate.py
